database:
  #  db: "heco_test:hDyhVaPfwvPzF8ek@tcp(bigdata-tidb-e604534a50b9d35d.elb.ap-northeast-1.amazonaws.com:4000)/chain_test?charset=utf8mb4"
  # db: "test:123@tcp(127.0.0.1:3306)/rebalance?charset=utf8mb4"
  db : "root:123456sj@tcp(localhost:3306)/rebalance?charset=utf8mb4"
  block_worker: 5
  tx_worker: 1
  sql_batch: 500
  retry_times: 5
  retry_interval: 300

app_name: rebalance
env: test20
apollo:
  appname: rebalance
  profile: default

bridge_conf:
  #url: "http://cex-bridge-api.test-15.huobiapps.com/cex-bridge-api/v1"
  url: "http://cex-bridge-api2.tctest-1.tc-jp1.huobiapps.com/cex-bridge-api/v1"
  timeout: "10s"
  ak: "vmiNuhGtCVBEzo4lRjf3qXcb26ITHwA0"
  sk: "z9wvRAjU5cOpBKi13th0x2VP4kfXLDus"

is_check_params: true

chains:
  heco:
    id: 128
    rpc_url: "https://http-mainnet.hecochain.com"
    timeout: 3000
    bridge_address: "0xd02c3f75dff68e787f028e7214f1089a7c9be5b9"
    block_safe: 20
  bsc:
    id: 56
    rpc_url: "https://bsc-dataseed.binance.org"
    timeout: 3000
    bridge_address: "0xba1828f24220c8f2ffcb790787a1a7a0d6e7e1c9"
    block_safe: 15
  polygon:
    id: 137
    rpc_url: "https://polygon-rpc.com"
    fetch_timeout: 3000
    bridge_address: "0x83b39565a8632f9e7f8d6ed1cb4850481d956510"
    block_safe: 128



api:
  margin_url: "http://localhost:8088/v1/auto-transfer/impermanent-loss-margin-preparing-job/"
  margin_out_url: "http://localhost:8088/v1/auto-transfer/all-margin-balance-transfer-out-job/"
  lp_url: "http://localhost:8088/v1/open/re"
  task_manager: "http://localhost:8088/"

margin:
  app_id: "rebalance-test"
  secret_key: "k0uKyWwYZdaaEIaO"

log:
  stdout:
    enable: true
    level: 5
  file:
    enable: true
    path: "/tmp/hermes-rebalance/app.log"
    level: 4
  kafka:
    enable: true
    topic: "applog-heco"
    kafka_servers:
      - "kafka-01.sinnet.huobiidc.com:9092"
      - "kafka-02.sinnet.huobiidc.com:9092"
      - "kafka-03.sinnet.huobiidc.com:9092"
      - "kafka-04.sinnet.huobiidc.com:9092"
      - "kafka-05.sinnet.huobiidc.com:9092"
      - "kafka-06.sinnet.huobiidc.com:9092"
    level: 5

server_conf:
  users:
    admin: "10244201"
