database:
  #  db: "heco_test:hDyhVaPfwvPzF8ek@tcp(bigdata-tidb-e604534a50b9d35d.elb.ap-northeast-1.amazonaws.com:4000)/chain_test?charset=utf8mb4"
  # db: "test:123@tcp(127.0.0.1:3306)/rebalance?charset=utf8mb4"
  db : "root:12345678@tcp(huobichain-dev-01.sinnet.huobiidc.com:3306)/rebalance?charset=utf8mb4"
  block_worker: 5
  tx_worker: 1
  sql_batch: 500
  retry_times: 5
  retry_interval: 300

bridge_conf:
  url: "http://cex-bridge-api.test-15.huobiapps.com/cex-bridge-api/v1"
  timeout: "10s"
  ak: "kB01A8gsMv2CP4Tctd7XnUaG3iDE9rQJ"
  sk: "ho8XcsfygSKTLEvPYOZ9W12k0i4IFJbC"

chains:
  heco:
    rpc_url: "https://http-mainnet.hecochain.com"
    fetch_timeout: 3000
  bsc:
    rpc_url: "https://bsc-dataseed.binance.org"
    fetch_timeout: 3000

from_addrs:
  HECO: "0x9f0583a209fedbc404c4968e2157c2e7d4359803"
  BSC: "0x74938228ae77e5fcc3504ad46fac4a965d210761"

log:
  stdout:
    enable: true
    level: 5
  file:
    enable: true
    path: "/tmp/hermes-rebalance/app.log"
    level: 4
  kafka:
    enable: false
    topic: "huobi-test"
    kafka_servers:
      - "kafka-1.huobidev.com:9092"
      - "kafka-2.huobidev.com:9092"
      - "kafka-3.huobidev.com:9092"
    level: 3
